### ISSUE TITLE
Blocks don't drop

### ISSUE THREAD

**Issue by SapphireLynx** [puggan/mc-colorbricks#1]
I'm not sure if it's really me having incorrectly installed the mod or not, or if it's just not correctly written, but when I break the colored bricks with a stone pickaxe, it doesn't drop the bricks.  I tried with all the other pickaxes and it still doesn't drop it, even when I change the game rules for tiles to drop.  I opened up the mod and it doesn't seem to have the harvest level set.
I'm not going to edit it cause it's your mod, but lemme know when you fix it, cause it's a good mod.

**Comment by Vanblam** [comment]
Same Problem here..

**Comment by puggan** [comment]
Ah, forgot the Loot-tables, didn't noticed it when i tested in createive mode.
added in b0bc7b6
Included in release v1.0.0

**Comment by puggan** [comment]
Version v1.0.0 is now avaible on curseforge.
https://www.curseforge.com/minecraft/mc-mods/colorbricks/files/all
