### ISSUE TITLE
v1.2.0 for fabric doesnt work on 1.16.5 despite literally being listed as it

### ISSUE THREAD

**Issue by SpinnyBoiii** [puggan/mc-colorbricks#10]
its asking for java 16, so probably coded for 1.17

**Comment by puggan** [comment]
The build script is set to Java 8:
https://github.com/puggan/mc-colorbricks/blob/ba07f36f5c14c7b38f34ffc9a4c0dcb4e7d183d4/build.gradle#L9-L10

But think i tested it using Java 16/17, so should recompile it using Java 8, and then test it with Java 8.

**Comment by puggan** [comment]
@SpinnyBoiii can you test the new file (I'm at the office now, so can't test it yet)

Compiled with Java-11:
https://www.curseforge.com/minecraft/mc-mods/colorbricks/files/3367448

running `file` on both files gives:
colorbricks-fabric-1.16.5-1.2.0.jar: Zip archive data, at least v2.0 to extract (old)
colorbricks-fabric-1.16.5-1.2.0.jar: Zip archive data, at least v1.0 to extract (new)

**Comment by puggan** [comment]
Found the problem:
https://github.com/puggan/mc-colorbricks/blob/533e331a304fa3b7d786b732ca2647a2a310762d/src/main/resources/fabric.mod.json#L31-L31

**Comment by puggan** [comment]
New release:
https://www.curseforge.com/minecraft/mc-mods/colorbricks/files/3367750
