### ISSUE TITLE
Bricks can't be broken with pickaxe

### ISSUE THREAD

**Issue by Rayxanber** [puggan/mc-colorbricks#11]
Hello,

ColorBricks take a long time to mine with pick (or any other tool), behaving as if being mined with the wrong tool, and do not drop themselves when broken.

**Comment by puggan** [comment]
Confirmed in Fabric 1.17.1-1.2.1

**Comment by puggan** [comment]
Should be fixed for 1.17, avaible here:
https://github.com/puggan/mc-colorbricks/releases/tag/1.17.1-1.2.2-fabric

(Publishingit on CurseForge when generated and tested all version.)

**Comment by puggan** [comment]
tested on version 1,17,1-1.2.3 -> 1.20.1-1.2.3
