### ISSUE TITLE
(Suggestion)New Recipe

### ISSUE THREAD

**Issue by A-a-ron717** [puggan/mc-colorbricks#5]
I think this mod would be a lot better if the crafting recipe was 8 bricks surrounding 1 dye to get 8 of the colored bricks like the recipe for stained glass.

**Comment by puggan** [comment]
The current recipe is 1 item + 1 dye
https://github.com/puggan/mc-colorbricks/blob/76e44fad14eebb90fa3a0b20b71bcb2ec4e3813c/src/main/resources/data/colorbricks/recipes/color_white_bricks.json#L1-L15

Is the suggestion to add a recipe for doing 8 at the time, or to replace the old recipe?

**Comment by puggan** [comment]
![Screenshot from 2020-10-18 13-24-24](https://user-images.githubusercontent.com/866668/96366037-50be5a80-1145-11eb-8ea9-9a94cc56eeb3.png)

**Comment by puggan** [comment]
1.16.1-3 version published at:
https://www.curseforge.com/minecraft/mc-mods/colorbricks/files/3085265

**Comment by A-a-ron717** [comment]
Thank you so much! This is perfect!

**Comment by puggan** [comment]
should make a 1.2.0 release for fabric and for forge 1.14 & 1.15 too, so reopening this.

**Comment by puggan** [comment]
1.2.0 now avaible for Forge 1.13-16 and Fabric 1.16-17
![ColorBricks-1 2 0](https://user-images.githubusercontent.com/866668/123555053-9676fc80-d783-11eb-9b55-bc62fd172c63.png)
