### ISSUE TITLE
Incompatible with 1.16.4

### ISSUE THREAD

**Issue by Dontrell94** [puggan/mc-colorbricks#8]
Mod currently requires below version 35 of forge to load. Version 35 is required to load Minecraft 1.16.4.

**Comment by puggan** [comment]
If it's just changeing the version numbers, I hope to have it fixed tomorrow.

**Comment by ruby8816** [comment]
it works fine now, whether that be because it was fixed or if it's just me

**Comment by puggan** [comment]
Forge-1.16.5 and Fabric-1.17 released
